name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Verify Java
        run: |
          java -version
          javac -version
          mvn -v

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile with Maven
        run: mvn -B -V clean compile

      - name: Build Docker Image
        run: docker build -t devopsimage .

      - name: Run image
        run: docker run --name devopscontainer -d devopsimage

      - name: View logs
        run: docker logs devopscontainer
