name: Build, Dockerize and Run Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'adopt'   # you can change to 'temurin' if preferred

      - name: Compile & package with Maven
        run: mvn -B package

      - name: Show current directory and files (debug)
        run: |
          echo "PWD: $(pwd)"
          echo "Listing top-level files:"
          ls -la
          echo "Find any Dockerfile:"
          find . -maxdepth 4 -iname Dockerfile -print || true
          echo "Show DeveOP folder contents:"
          ls -la DeveOP || true
          echo "Show target contents in DeveOP (if present):"
          ls -la DeveOP/target || true

      - name: Build Docker Image (use DeveOP/Dockerfile as source)
        # Build using the DeveOP folder as context and the Dockerfile inside it
        run: |
          docker build -f DeveOP/Dockerfile -t devopsimage DeveOP

      - name: Remove old container if exists
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^devopscontainer$'; then
            docker rm -f devopscontainer || true
          fi

      - name: Run image
        run: docker run --name devopscontainer -d devopsimage

      - name: View logs
        run: docker logs --tail 200 devopscontainer || true

      - name: Show running containers (debug)
        run: docker ps -a || true
